import {
  createNewLine,
  moveup,
  movedown,
  moveLeft,
  moveRight,
  isHashtag,
  createHashtag,
  isMention,
  createMention,
  isURL,
  createBetweenSpan,
  createNormalSpan,
  setCursorPosition,
  hasLink,
  getContainerElement,
} from "./text-editor";

export {
  createNewLine,
  moveup,
  movedown,
  moveLeft,
  moveRight,
  isHashtag,
  createHashtag,
  isMention,
  createMention,
  isURL,
  createBetweenSpan,
  createNormalSpan,
  setCursorPosition,
  hasLink,
  getContainerElement,
};
