import {
  createNewLine,
  moveup,
  movedown,
  createNormalSpan,
  setCursorPosition,
  hasLink,
  getCurElement,
  deleteByBackspace,
  moveStart,
  moveEnd,
  movePageUp,
  movePageDown,
  selectToEnd,
  selectToStart,
  selectWithPgUp,
  selectWithPgDn,
  selectWithArrowRight,
  selectWithArrowLeft,
  selectWithArrowUp,
  selectWithArrowDown,
  initializeSelection,
} from "./text-editor/text-editor";

import { moveRight, moveLeft } from "./text-editor/move";

import { varifySelected } from "./text-editor/varify";

export {
  createNewLine,
  moveup,
  movedown,
  moveLeft,
  moveRight,
  createNormalSpan,
  setCursorPosition,
  hasLink,
  getCurElement,
  deleteByBackspace,
  moveStart,
  moveEnd,
  movePageUp,
  movePageDown,
  selectToEnd,
  selectToStart,
  selectWithPgUp,
  selectWithPgDn,
  selectWithArrowRight,
  selectWithArrowLeft,
  selectWithArrowUp,
  selectWithArrowDown,
  initializeSelection,
  varifySelected,
};
